# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'PageKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'

#Debug
pod 'Reveal-SDK', '~> 4', :configurations => ['Debug']
end
